### ISSUE TITLE
Errors on elm-test

### ISSUE THREAD

**Issue by tasuki** [piotr-semenov/elm-docker#1]
On a project of mine:
```
$ alias elm-test='docker run --rm --entrypoint "elm-test" -v `pwd`:/workdir -v `pwd`/.elm:/.elm -w /workdir -e http_proxy -e https_proxy semenovp/tiny-elm:all-latest'
$ elm-test
Downloading elm-json 0%
Failed to download:
< https://github.com/zwilias/elm-json/releases/download/v0.2.10/elm-json-v0.2.10-x86_64-unknown-linux-musl.tar.gz
> /.elm/elm-tooling/elm-json/0.2.10/elm-json
tar must be installed on your system and be in $PATH:
spawn tar ENOENT
```

When I put the `elm-json` from that url into `.elm/elm-tooling/elm-json/0.2.10/elm-json` I get:
```
$ elm-test
Solving dependencies > Compiling > Starting tests
Error: listen EACCES: permission denied /tmp/elm_test-1.sock
    at Server.setupListenHandle [as _listen2] (node:net:1293:21)
    at listenInCluster (node:net:1358:12)
    at Server.listen (node:net:1456:5)
    at /usr/local/lib/node_modules/elm-test/lib/Supervisor.js:266:12
    at new Promise (<anonymous>)
    at Object.run (/usr/local/lib/node_modules/elm-test/lib/Supervisor.js:19:10)
    at run (/usr/local/lib/node_modules/elm-test/lib/RunTests.js:245:31)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

:shrug:

**Comment by piotr-semenov** [comment]
Hi @tasuki!
Can you please share your elm.json and tests? I am not a real Elm developer, so your project will be very helpful to resolve the second part of your issue.
First part of your issue is clear to me. And a single line edit to Dockerfile will fix it.

**Comment by tasuki** [comment]
@piotr-semenov thank you for your quick reply! And for dockerizing Elm development! (I see my initial issue looks a bit... curt? It wasn't meant that way!)

The [elm.json this happened on was this one](https://github.com/tasuki/sniper/blob/master/elm.json), I think. Fwiw I don't have a pressing need to get this resolved, just wanted to let you know :slightly_smiling_face:
